apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-ui-deployment
  labels:
    app: notification-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-ui
  template:
    metadata:
      labels:
        app: notification-ui
    spec:
      containers:
        - name: notification-ui
          image: mathiskretz/notification-ui
          ports:
            - containerPort: 80
          env:
            - name: BACKEND_BASE_URL
              value: "http://104.199.66.38"
